version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=warehouse'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432